### ISSUE TITLE
Hue can't get discovered

### ISSUE THREAD

**Issue by christiandufner** [LMS0815/OctoPrint-hueCommands#2]
Hi,

hue can't get discovered. 
When i enter die ip manually, i get the Device name: OctoPrint hue Commands#125287
Then i press the hue button but it doesnt work.
This procedure i can do from hue website sucsessfully & it works from the app.

Any suggestions?

Kind regards,
Christian

**Comment by LMS0815** [comment]
Hi,

discover has an issue and is only working with certain configurations.
Entering the IP manually is the best method.  If you have the name (e.g. OctoPrint hue Commands#125287) pairing should work if you first hit the hue button and afterwards click the connect button of the plugin.

**Comment by christiandufner** [comment]
I just tried that (again), got the name: OctoPrint hue Commands#39b950 but connecting didn't work :/ Is there any workaround?

**Comment by LMS0815** [comment]
You could use any credentials. 
See: https://developers.meethue.com/develop/get-started-2/

**Comment by LMS0815** [comment]
Unfortunately I can not find any solution to improve discover.
